apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jhipster-kafka
  namespace: stream-analyzer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jhipster-kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:1.0.0
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: jhipster-kafka.stream-analyzer.svc.cluster.local
        - name: KAFKA_ADVERTISED_PORT
          value: '9092'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: jhipster-zookeeper.stream-analyzer.svc.cluster.local:2181
        - name: KAFKA_CREATE_TOPICS
          value: 'topic-jhipster:1:1'
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: jhipster-kafka
  namespace: stream-analyzer
spec:
  selector:
    app: jhipster-kafka
  ports:
  - port: 9092
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jhipster-zookeeper
  namespace: stream-analyzer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jhipster-zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:3.4.6
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: jhipster-zookeeper
  namespace: stream-analyzer
spec:
  selector:
    app: jhipster-zookeeper
  ports:
  - port: 2181
